import React from 'react';

const Introduction = () => {
  return (
    <div id="intro">
      <h3>INTRODUCTION</h3>
            <p>New York City, one of the world's busiest cities, is home to a 
                diverse range of neighbourhoods, cultures, and dynamics. As 
                such, policing this city requires evidence-based strategies that 
                are both effective and equitable. The NYPD Arrest Data (Year 
                to Date) dataset provides a wealth of information, including the 
                type of crime, location,  time of enforcement, and suspect 
                demographics. The New York City Police Department (NYPD) 
                Arrest Data  (Year to Date) dataset, available on data.gov, is a 
                comprehensive repository of information regarding arrests made  
                within the city. This dataset offers a unique opportunity to 
                investigate the particulars of law enforcement, crime, and 
                community dynamics in New York City's diverse and dynamic 
                geography. The NYPD's goal is to safeguard public safety, 
                uphold the law, and build positive relationships with the 
                community, thus it is vital to scrutinize and interpret the massive 
                amounts of data generated by these operations. This project aims 
                to analyze the NYPD Arrest Data using data science and 
                analytics to answer crucial questions regarding crime patterns, 
                law enforcement practices, and community impact. We 
                recognize the significance of this endeavor considering its potential to not only inform policing policies, but also to 
                improve transparency, accountability, and public trust in law 
                enforcement institutions. [1] Through an in-depth analysis of the 
                NYPD arrest data, this project seeks to shed light on the current 
                state of crime and the effectiveness of law enforcement  
                strategies. By leveraging this data, we aim to uncover patterns 
                and trends that can inform policing strategies and contribute to 
                public safety. [2] </p>
    </div>
  );
};

export default Introduction;
